version: '3'

services:
  db:
    image: postgres:17-alpine3.20
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: baseAPI-db
    volumes:
      - ./postgres:/var/lib/postgresql/data